version: '3'
services:
  xds-server:
    build:
      context: .
      dockerfile: Dockerfile-xds-server
    # command: ["go", "run", "/go/src/Envoy-xDS/cmd/server/main.go"]
    security_opt:
      - seccomp:unconfined
    command:
      - /bin/sh
      - -c
      - |
          dlv debug Envoy-xDS/cmd/server/ -l 0.0.0.0:2345 --headless=true --log=true -- server
    ports:
     - "8080:8080"
     - "9901:9901"
     - "2345:2345"
     - "7777:7777"